apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-app
data:
  ENV: dev
  REQUIREMENTS_FILE: config/requirements/dev.txt
  DJANGO_SETTINGS_MODULE: config.settings.dev
  REDIS_URL: redis://redis:6379
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_DB: tunnelking
  POSTGRES_USER: postgres
  DEBUG: "True"
  DJANGO_DB_HOST: postgres
  DJANGO_DB_USER: postgres
  DJANGO_DB_PORT: "5432"
  DJANGO_DB_NAME: tunnelking
  EMAIL_HOST: smtp.gmail.com
  EMAIL_USE_TLS: "True"
  EMAIL_PORT: "587"
  ALLOWED_HOSTS: "127.0.0.1:8000"
  CORS_ALLOWED_ORIGINS: "mysite.com,mysite2.com,localhost"
