apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: django-app
type: Opaque
data:
  DJANGO_SECRET_KEY: ZGFuZ2tvLWluc2VjdXJlLXdsZ2p1bzUzWTQ5JS00eTUoISVrc3lsbGVfdWRlYi03JV9fQDhIaCtAJGQlXjNzej8=
  DJANGO_DB_PASSWORD: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  EMAIL_HOST_PASSWORD: bXl2ZXJ5c3Ryb25ncGFzc3dvcmQ=
  SENTRY_DSN: aHR0cHM6Ly9leGFtcGxlUHVibGljS2V5QG8wLmluZ2VzdC5zZW50cnkuaW8vMA==
