# Generated by Django 5.1.5 on 2025-01-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0001_initial"),
        ("organization", "0002_document"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="downloadedmodel",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="downloadedmodel",
            unique_together={("model", "organization")},
        ),
    ]
